### ISSUE TITLE
"Created by" user  should be made available in Data exports of Beneficiary, Tickets, Rescue and Daily report

### ISSUE THREAD

**Issue by Nikhilgeo2** [frappe/changemakers#113]
Harsh Suggested it can be done with a new field in form, which will be hidden, but auto populate as and when a new entry is created

**Comment by Nikhil-Jorge** [comment]
Please prioritise this

**Comment by Nikhil-Jorge** [comment]
As suggested by you - if we get username in export that will be helpful.

Please dont close issues unless it is not in live instance of bangalore. **https://bangalore.dignifiedlife.in/**
