### ISSUE TITLE
We should be able to multiselect in filters (Wards in Beneficiary list)

### ISSUE THREAD

**Issue by Nikhilgeo2** [frappe/changemakers#114]
For Example - the present need is , Mehran needs to have filter with 15 wards selected for beneficiary list. He tried Comma seperated values but it is allowed only for 140 character.

1. Either change validation to 600 characters
2. There should be any easy way for multi select filters, atleast for selecting multiple wards in Beneficiary list. 

Please take this as a priority

**Comment by jagadishaapf** [comment]
This is critical for go live @umairsy  @harshtandiya @NagariaHussain

**Comment by harshtandiya** [comment]
To set up the max character limit of any field you want to be filtered, you have to change the `length` of that field through `customize form`. 

For Wards in Beneficiary List, do the following: 

- Go to Customize Form using [AwesomeBar](https://frappeframework.com/docs/user/en/desk#awesomebar)
![image](https://github.com/frappe/changemakers/assets/73123690/483c253c-74e6-4ec6-8218-9c2d64651419)
- Select **Beneficiary** in _Enter Form Type_
- Scroll down and select the field for which you want to increase the length. In this case `Ward/GP`
![image](https://github.com/frappe/changemakers/assets/73123690/50421a32-770b-4067-b033-8dd8a79021aa)
- In `Length` field, set the limit. In this case: 600
![image](https://github.com/frappe/changemakers/assets/73123690/c9aa4c0f-5400-4c59-b406-d0f21381e79b)
- Update the form
![image](https://github.com/frappe/changemakers/assets/73123690/a2c2a524-844a-46f2-8751-e4c33eb014a0)


Let me know if it works out.
