### ISSUE TITLE
Edited by or comment by users - Shall we get it by Username

### ISSUE THREAD

**Issue by Nikhil-Jorge** [frappe/changemakers#119]
and not email ID. Since social workers are given email id s - psw01, 02 etc - it is difficult to trace who made what edit. If in the details we can see edited by **Sultan Pasha instead of ' by 'psb.sw07@gmail.com'** its easier and convenient.

**Comment by harshtandiya** [comment]
Should I do the same for Created By field for export? right now it pulls up the email

**Comment by Nikhil-Jorge** [comment]
Yes..  thats better. other wise we always have to resort to lookups in excel downloads

**Comment by Nikhil-Jorge** [comment]
Tested by Mehran
