### ISSUE TITLE
Unable to Open Health Camp 

### ISSUE THREAD

**Issue by Nikhil-Jorge** [frappe/changemakers#126]
It throws an error quoting a newly created Doctype- MCRC daily update . Please fix this

**Comment by harshtandiya** [comment]
Can you attach a screenshot and paste the error here?

**Comment by Nikhil-Jorge** [comment]
![image](https://github.com/frappe/changemakers/assets/120703161/22c4edff-08f3-43a3-8291-631f8dc55966)
