### ISSUE TITLE
Active partner or not should be visible in tickets export

### ISSUE THREAD

**Issue by Nikhil-Jorge** [frappe/changemakers#127]
Right now, when we select a beneficiary  in a ticket,  age and gender fields come up as extra fields. Can we add a field for active partners also - which will be fetched from Beneficiary

**Comment by harshtandiya** [comment]
I cannot see an "Active Partner" field in the Beneficiary doctype. Is this something that was custom at your end?

**Comment by Nikhil-Jorge** [comment]
![image](https://github.com/frappe/changemakers/assets/120703161/fa7bcc59-bed6-43ac-8535-765a1947a4d4)


YES IT IS!

**Comment by harshtandiya** [comment]
Perhaps, in tickets add another field "Active Partner" through Customize Form.

And fetch `Active Partner` field from Beneficiary
![image](https://github.com/frappe/changemakers/assets/73123690/c93efb7f-f9bb-4bfb-91ce-206d2a85f51c)

As it is custom on your end, I would not like to avoid the chances of breaking anything by duplicating the active partner field from my side. It is pretty straightforward, but please let me know if you need any help.

**Comment by Nikhil-Jorge** [comment]
Yes. I need a help. If the benefiary we select is active partner , we should fetch that. Do I need to create a link datatype in the form?

**Comment by harshtandiya** [comment]
@Nikhil-Jorge Tickets already have a link to beneficiary doctype. But if you want to implement fetching in some other doctype, you will require a link field to the doctype you wanna fetch from.

You can learn more about fetching from here: [Fetch From: All About DocType Form in Frappe Framework - Build With Hussain](https://www.youtube.com/watch?v=78Yp_OdXnBI)

**Comment by Nikhil-Jorge** [comment]
Done. thanks for the support.

**Comment by Nikhil-Jorge** [comment]
.
