### ISSUE TITLE
We need a child table in Ticket/cases for Capturing Payment details if any

### ISSUE THREAD

**Issue by Nikhil-Jorge** [frappe/changemakers#130]
This should be reflected in both instances. Will Discuss over a call

**Comment by Nikhil-Jorge** [comment]
This should be done in Changemakers App - (and not a customisation for Bangalore Instance)

A child table for Capturing Payment details and a field for auto-populating total Payment.

The format would be:

![image](https://github.com/frappe/changemakers/assets/120703161/b71c1e62-51fe-4f2e-8d77-16374e40daa2)

**Comment by Nikhil-Jorge** [comment]
Payment Type to be a doctype, with entries (Consultation, Testing, Medicine) . we will add more Payment Types on the go.

Total Payment to be a seperate field

**Comment by Nikhil-Jorge** [comment]
Payment Details can be placed just above follow up table

**Comment by maniamartial** [comment]
I was working on this issue, but I don't really understand this
"Payment Type to be a doctype, with entries (Consultation, Testing, Medicine) . we will add more Payment Types on the go."

**Comment by Nikhil-Jorge** [comment]
> I was working on this issue, but I don't really understand this "Payment Type to be a doctype, with entries (Consultation, Testing, Medicine) . we will add more Payment Types on the go."

If we have a doc type created for Payment type, we can see payment type as a dynamic dropdown, meaning options can be addded on the go, by the person who enters data. Discussed this with Harsh

**Comment by maniamartial** [comment]
@Nikhil-Jorge Yeah, I took care of that
