### ISSUE TITLE
A new Form For CRC Admissions

### ISSUE THREAD

**Issue by Nikhil-Jorge** [frappe/changemakers#132]
A form needed to be created and added to the WorkSpace

**Comment by Nikhil-Jorge** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/NIKHIL~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/NIKHIL~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | Fields | Type | Eg |   |  
-- | -- | -- | -- | -- | --
1 | Name of Facility | Dropdown | MCRC (Female) |   |  
2 | Doctors Name | Text |   |   |  
3 | Name of the   Benficiary | Select |   |   |  
4 | File Number | Data |   |   |  
5 | Date of Admission | Date |   |   |  
  |   |   |   |   |  
6 | Type of Admission |   | voluntary/Involuntary |   |  
7 | Refered By | DD | Police, PS -   Partners, Self |   |  
  |   |   |   |   |  
8 | Medical Conditions | DD - Multiselect |   |   |  
9 | Descriptive - to be   filled in by Doctor | Text |   |   |  
10 | Estimated Duration in   Days | Number |   |   |  
  |   |   |   |   |  
11 | Actual Duration | (Calculated Field   : Date - Date of admission) |   |   |  
  |   |   |   |   |  
12 | Child Table: |   |   |   |  
  | Sl.no (Auto) | Date | Time | Category | Description
  | 1 |   |   | Tests/ Medication/   x/y (Select) | Text
  |   |   |   |   | add row
13 | Date of Discharge | Date |   |   |  
14 | Exit Pathway | DD | Family reintegration, Death, Shelter   Home |   |  



</body>

</html>

**Comment by maniamartial** [comment]
What does DD means?

**Comment by NagariaHussain** [comment]
Dropdown I guess 😅, @Nikhil-Jorge ?

**Comment by maniamartial** [comment]
😂Ok, will check out and work on this on weekend

**Comment by Nikhil-Jorge** [comment]
Yes. Its dropdown

**Comment by maniamartial** [comment]
The **child Table 12**, which field will it be linked to?
If its medical condition, then can we do away with **descriptive(to be filled by doctor** and let the doctor fill the child table?

**Comment by maniamartial** [comment]
https://github.com/frappe/changemakers/assets/60258622/83394e40-d5c6-4ddf-9b21-144199e91108

Anything I took wrong, let me know

**Comment by NagariaHussain** [comment]
Completed in https://github.com/frappe/changemakers/pull/137
