### ISSUE TITLE
Error in CRC Capacity Calculation

### ISSUE THREAD

**Issue by Nikhil-Jorge** [frappe/changemakers#138]
Logic is 

If status is either 'hospitalised' or 'Admitted'  it should be bed occupied. Meaning vacant beds should be total - occupied.

This is currently taking only Hospitalised and not admitted. Please correct.

**Comment by hraza01** [comment]
Hi @Nikhil-Jorge,

I believe that the logic for calculating vacant beds is already taking both "Hospitalised" and "Admitted" into account when calculating vacant beds. If you can provide steps to reproduce this, then i can investigate further.
