### ISSUE TITLE
Multiple Fields to be made non mandatory in Chennai Instance

### ISSUE THREAD

**Issue by Nikhil-Jorge** [frappe/changemakers#139]
As You know, System manager can't make any mandatory fields to non mandatory.

For Chennai Instances below should be made non mandatory

1. Rescue
     Rescue location - ( map picker) to be made as non mandatory.
  
2. Tickets
    Prioirty -to be made as non mandatory.
    State, District, Zone, Ward - to be made non mandatory for chennai.

3. Awareness Camp ( renamed in chennai as events and camps) 
   State, District, Zone, Ward - to be made non mandatory for chennai.

4. Health Camp 
    State, District, Zone, Ward - to be made non mandatory for chennai.

**Comment by NagariaHussain** [comment]
I have made the fields non mandatory (d479384eb0885ab8b286832742f0aa94432f1c8c), @Nikhil-Jorge you can use the customise form to make fields mandatory wherever required.

Side note / learning: applying too many validations/constrains at the initial stages is not a good idea 😉
