### ISSUE TITLE
Identity proof length and districts data

### ISSUE THREAD

**Issue by ph4ni** [frappe/changemakers#142]
In the entitlement table, Identity proof column "Number" is int which does not allow 12-digit numbers like Aadhaar. Throws "Frappe integer truncated as characters allowed is 2147483647". I temporarily changed the Type to "Data" but is there a better solution? 

The District list is empty. The documentation says districts/city data is pre-populated. Should I import the data from another source myself?

**Comment by NagariaHussain** [comment]
There is a script to import district and states from government API:

```sh
bench --site <site-name> execute changemakers.utils.data.scrap_and_import_india_district_list
```

I will added this to after install as well, but sometimes it fails.
