### ISSUE TITLE
Hygiene as a ticket type

### ISSUE THREAD

**Issue by Nikhil-Jorge** [frappe/changemakers#90]
Ticket type right now is only 'select'. Better to create a Doctype for Ticket type. 

Hygiene need to be shown as a ticket type ASAP

**Comment by NagariaHussain** [comment]
@harshtandiya Let's change the select field to link field and we might need to write a patch to fix the existing data.

**Comment by harshtandiya** [comment]
Done. Check PR #93

**Comment by Nikhil-Jorge** [comment]
i am not able to see this in the ticket types of bangalore instance
