### ISSUE TITLE
People Attending Each Health Camps

### ISSUE THREAD

**Issue by Nikhil-Jorge** [frappe/changemakers#91]
In the Patients-screened Section of Health Camp, functionality to add all active clients who got screened (linelisting) to be added. 

This can be a table from where, Health coordinator and Social workers can add the list of all active clients who participated in the health camp

**Comment by NagariaHussain** [comment]
Client as in beneficiaries, right @Nikhil-Jorge ?

**Comment by Nikhil-Jorge** [comment]
Yes yes. Active clients/ Active partners are the name used to identify ~450 homeless beneficiaries, whom we have good visibility. The purpose is also to know about health seeking behaviour at an individual level.

**Comment by NagariaHussain** [comment]
Cool, makes sense 👍

**Comment by Nikhil-Jorge** [comment]
As per Video shared. this is almost fine. Only modification is Social worker need to see - Name-hotspot name- Age to identify the right beneficiary.

I could not test this, as this is not available in Bangalore instance and Staging , when I checked.
